<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/10 0010
 * Time: 16:52
 */

namespace app\admin\controller;

class Basecontroller extends \app\common\controller\Commoncontroller
{
    /**
     * 初化化方法
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $flag = $this->isLogin();
        if (!$flag) {
            $this->error('请先登录', '/index.php/admin/login/index');
        }
    }

    public function isLogin()
    {
        $userInfo = session(config('admin.session_userinfo'), '', config('admin.session_userinfo_scope'));
        if ($userInfo && $userInfo['id'] && $userInfo['username'] && $userInfo['id']) {
            return true;
        } else {
            return false;
        }
    }

}
