<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/10 0010
 * Time: 17:00
 */

namespace app\bis\controller;

class Basecontroller extends \app\common\controller\Basecontroller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        echo('application/bis/controller/Basecontroller.php<br>');
    }
}