<?php
/**
 * Created by PhpStorm.
 * User: sf
 * Date: 2017/10/21
 * Time: 17:12
 */

namespace app\home\controller;

class Register extends \app\home\controller\Basecontroller
{
    public $memberUsername;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->memberUsername = $this->memberUname;
    }

    /**
     * 会员注册
     * @return array|mixed|void
     */
    public function index()
    {
        $data = input('post.');
        if ($data) {
            if (!captcha_check($data['verifycode'])) return show(0, '请输入正确的验证码');
            if (trim($data['rpassword']) != trim($data['password'])) return show(0, '密码不一致');
            if (model('Member')->getMemberuserByUsername(trim($data['username']))) return show(0, '此用户名已存在');
            if (model('Member')->getMemberuserByEmail(trim($data['email']))) return show(0, ',此邮件已注册');
            $data['password'] = getVdouwMD5($data['password']);
            $resId = model('Member')->add($data);
            session('memberUserSession', json_encode($data), 'memberUserSession');
            cookie('memberUserCookie', json_encode($data));
            if ($resId) {
                return show(1, "添加成功", $resId);
            }
            return show(0, '添加失败', $resId);
        } else {
            return $this->fetch('', [
                'memberUsername' => $this->memberUsername
            ]);
        }
    }

    public function verify()
    {
        $config = [
            'fontSize' => 50, // 验证码字体大小
            'length' => 4, // 验证码位数
            'useNoise' => false, // 关闭验证码杂点
            'codeset' => '2345678wertyuipkjhgfdsazxcvbnmQWERTYUPLKJHGFDSAZXCVBN'
        ];
        $captcha = new \think\captcha\Captcha($config);
        return $captcha->entry();
    }
}